metricbeat.config.modules:
  path: /usr/share/metricbeat/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

metricbeat.modules:
- module: postgresql
  metricsets:
    - database
    - bgwriter
    - activity
  period: 10s
  hosts: ["postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable"]

- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
    - filesystem
    - fsstat
  period: 10s
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  period: 10s
  hosts:
    - "unix:///var/run/docker.sock"
  condition:
    contains:
      docker.container.name: "postgres"

name: ${METRICBEAT_NAME}
agent.id: ${METRICBEAT_NAME}-${METRICBEAT_FIELDS_DATACENTER}

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

setup.kibana:
  host: "${KIBANA_HOST}"

setup.dashboards.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.ilm.enabled: true
setup.ilm.rollover_alias: "metricbeat"
setup.ilm.pattern: "{now/d}-000001"

logging.level: ${METRICBEAT_LOG_LEVEL}
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 7
  permissions: 0644

monitoring.enabled: ${METRICBEAT_MONITORING_ENABLED}

http.enabled: true
http.host: 0.0.0.0
http.port: 5068

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
