volumes:
    nginx-data:
        name: nginx-data
        driver: local
    mongodb-data:
        name: mongodb-data
        driver: local
    dicebear-data:
        name: dicebear-data
        driver: local
    sonarqube_temp:
        name: sonarqube_temp
        driver: local
    sonarqube_data:
        name: sonarqube_data
        driver: local
    sonarqube_logs:
        name: sonarqube_logs
        driver: local
    sonarqube_extensions:
        name: sonarqube_extensions
        driver: local

services:
    nginx-service:
        build:
            context: .
            dockerfile: ./compose/nginx/dockerfile
        image: nginx-service:latest
        container_name: nginx-service
        ports:
            - "8080:8080"
        volumes:
            - nginx-data:/var/lib/nginx
        networks:
            - initstack
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        depends_on:
            dicebear-service:
                condition: service_healthy

    backend-service:
        build:
            context: .
            dockerfile: ./compose/backend/dockerfile
        image: backend-service:latest
        container_name: backend-service
        env_file:
            - ./.envs/backend/.env
        volumes:
            - .:/app:z
        networks:
            - initstack
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
        depends_on:
            mongodb-service:
                condition: service_healthy
            dicebear-service:
                condition: service_healthy

    mongodb-service:
        image: mongo:latest
        container_name: mongodb-service
        ports:
            - "27017:27017"
        env_file:
            - ./.envs/mongodb/.env
        volumes:
            - mongodb-data:/data/db
        networks:
            - initstack
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "'db.hello().ok'"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s

    dicebear-service:
        build:
            context: .
            dockerfile: ./compose/dicebear/dockerfile
        image: dicebear-service:latest
        container_name: dicebear-service
        volumes:
            - dicebear-data:/var/lib/dicebear
        networks:
            - initstack
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-f",
                    "http://localhost:3000/9.x/avataaars/svg?seed=John%20Doe&accessories[]&eyebrows=default,defaultNatural&eyes=default,happy,squint&mouth=default,smile",
                ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

    sonarqube-service:
        image: sonarqube:latest
        container_name: sonarqube-service
        ports:
            - "9000:9000"
        env_file:
            - ./.envs/sonarqube/.env
        volumes:
            - sonarqube_temp:/opt/sonarqube/temp
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_extensions:/opt/sonarqube/extensions
        networks:
            - initstack
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

networks:
    initstack:
        name: initstack
        driver: bridge
