#!/bin/bash

# Exit On Error
set -o errexit
# Fail On Undefined Variables
set -o nounset

# Start Celery Flower With Authentication
exec celery -A app.config.celery_app flower --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
