#!/bin/sh

# Exit On Error
set -o errexit
# Fail On Undefined Variables
set -o nounset

# Wait For Dependencies To Be Ready
echo "Waiting For Dependencies To Be Ready..."
sleep 120

# Start Backend Application
echo "Starting Backend Application..."
exec python -m watchfiles "python -m app"
